# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: information.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11information.proto\"\xb2\x03\n\x0bInformation\x12\n\n\x02sn\x18\x01 \x01(\t\x12\x1d\n\x03\x63pu\x18\x02 \x01(\x0b\x32\x10.Information.Cpu\x12\x1f\n\x04\x64sp1\x18\x03 \x01(\x0b\x32\x11.Information.Dsp1\x12\x1f\n\x04\x64sp2\x18\x04 \x01(\x0b\x32\x11.Information.Dsp2\x12#\n\x06\x65rrors\x18\x08 \x01(\x0b\x32\x13.Information.Errors\x1a\x32\n\x03\x43pu\x12\r\n\x05major\x18\x01 \x01(\x05\x12\r\n\x05minor\x18\x02 \x01(\x05\x12\r\n\x05\x62uild\x18\x03 \x01(\x05\x1a\x33\n\x04\x44sp1\x12\r\n\x05major\x18\x01 \x01(\x05\x12\r\n\x05minor\x18\x02 \x01(\x05\x12\r\n\x05\x62uild\x18\x03 \x01(\x05\x1a\x33\n\x04\x44sp2\x12\r\n\x05major\x18\x01 \x01(\x05\x12\r\n\x05minor\x18\x02 \x01(\x05\x12\r\n\x05\x62uild\x18\x03 \x01(\x05\x1as\n\x06\x45rrors\x12\x32\n\nloggerList\x18\x01 \x03(\x0b\x32\x1e.Information.Errors.LoggerList\x1a\x35\n\nLoggerList\x12\x14\n\x0c\x63ontrollerid\x18\x01 \x01(\x05\x12\x11\n\tsubsystem\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'information_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INFORMATION._serialized_start=22
  _INFORMATION._serialized_end=456
  _INFORMATION_CPU._serialized_start=183
  _INFORMATION_CPU._serialized_end=233
  _INFORMATION_DSP1._serialized_start=235
  _INFORMATION_DSP1._serialized_end=286
  _INFORMATION_DSP2._serialized_start=288
  _INFORMATION_DSP2._serialized_end=339
  _INFORMATION_ERRORS._serialized_start=341
  _INFORMATION_ERRORS._serialized_end=456
  _INFORMATION_ERRORS_LOGGERLIST._serialized_start=403
  _INFORMATION_ERRORS_LOGGERLIST._serialized_end=456
# @@protoc_insertion_point(module_scope)
