# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: information.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='information.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11information.proto\"\xb2\x03\n\x0bInformation\x12\n\n\x02sn\x18\x01 \x01(\t\x12\x1d\n\x03\x63pu\x18\x02 \x01(\x0b\x32\x10.Information.Cpu\x12\x1f\n\x04\x64sp1\x18\x03 \x01(\x0b\x32\x11.Information.Dsp1\x12\x1f\n\x04\x64sp2\x18\x04 \x01(\x0b\x32\x11.Information.Dsp2\x12#\n\x06\x65rrors\x18\x08 \x01(\x0b\x32\x13.Information.Errors\x1a\x32\n\x03\x43pu\x12\r\n\x05major\x18\x01 \x01(\x05\x12\r\n\x05minor\x18\x02 \x01(\x05\x12\r\n\x05\x62uild\x18\x03 \x01(\x05\x1a\x33\n\x04\x44sp1\x12\r\n\x05major\x18\x01 \x01(\x05\x12\r\n\x05minor\x18\x02 \x01(\x05\x12\r\n\x05\x62uild\x18\x03 \x01(\x05\x1a\x33\n\x04\x44sp2\x12\r\n\x05major\x18\x01 \x01(\x05\x12\r\n\x05minor\x18\x02 \x01(\x05\x12\r\n\x05\x62uild\x18\x03 \x01(\x05\x1as\n\x06\x45rrors\x12\x32\n\nloggerList\x18\x01 \x03(\x0b\x32\x1e.Information.Errors.LoggerList\x1a\x35\n\nLoggerList\x12\x14\n\x0c\x63ontrollerid\x18\x01 \x01(\x05\x12\x11\n\tsubsystem\x18\x02 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INFORMATION_CPU = _descriptor.Descriptor(
  name='Cpu',
  full_name='Information.Cpu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major', full_name='Information.Cpu.major', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minor', full_name='Information.Cpu.minor', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='build', full_name='Information.Cpu.build', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=233,
)

_INFORMATION_DSP1 = _descriptor.Descriptor(
  name='Dsp1',
  full_name='Information.Dsp1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major', full_name='Information.Dsp1.major', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minor', full_name='Information.Dsp1.minor', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='build', full_name='Information.Dsp1.build', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=286,
)

_INFORMATION_DSP2 = _descriptor.Descriptor(
  name='Dsp2',
  full_name='Information.Dsp2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major', full_name='Information.Dsp2.major', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minor', full_name='Information.Dsp2.minor', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='build', full_name='Information.Dsp2.build', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=339,
)

_INFORMATION_ERRORS_LOGGERLIST = _descriptor.Descriptor(
  name='LoggerList',
  full_name='Information.Errors.LoggerList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='controllerid', full_name='Information.Errors.LoggerList.controllerid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subsystem', full_name='Information.Errors.LoggerList.subsystem', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=456,
)

_INFORMATION_ERRORS = _descriptor.Descriptor(
  name='Errors',
  full_name='Information.Errors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loggerList', full_name='Information.Errors.loggerList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_INFORMATION_ERRORS_LOGGERLIST, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=456,
)

_INFORMATION = _descriptor.Descriptor(
  name='Information',
  full_name='Information',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sn', full_name='Information.sn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cpu', full_name='Information.cpu', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dsp1', full_name='Information.dsp1', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dsp2', full_name='Information.dsp2', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errors', full_name='Information.errors', index=4,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_INFORMATION_CPU, _INFORMATION_DSP1, _INFORMATION_DSP2, _INFORMATION_ERRORS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=456,
)

_INFORMATION_CPU.containing_type = _INFORMATION
_INFORMATION_DSP1.containing_type = _INFORMATION
_INFORMATION_DSP2.containing_type = _INFORMATION
_INFORMATION_ERRORS_LOGGERLIST.containing_type = _INFORMATION_ERRORS
_INFORMATION_ERRORS.fields_by_name['loggerList'].message_type = _INFORMATION_ERRORS_LOGGERLIST
_INFORMATION_ERRORS.containing_type = _INFORMATION
_INFORMATION.fields_by_name['cpu'].message_type = _INFORMATION_CPU
_INFORMATION.fields_by_name['dsp1'].message_type = _INFORMATION_DSP1
_INFORMATION.fields_by_name['dsp2'].message_type = _INFORMATION_DSP2
_INFORMATION.fields_by_name['errors'].message_type = _INFORMATION_ERRORS
DESCRIPTOR.message_types_by_name['Information'] = _INFORMATION

Information = _reflection.GeneratedProtocolMessageType('Information', (_message.Message,), dict(

  Cpu = _reflection.GeneratedProtocolMessageType('Cpu', (_message.Message,), dict(
    DESCRIPTOR = _INFORMATION_CPU,
    __module__ = 'information_pb2'
    # @@protoc_insertion_point(class_scope:Information.Cpu)
    ))
  ,

  Dsp1 = _reflection.GeneratedProtocolMessageType('Dsp1', (_message.Message,), dict(
    DESCRIPTOR = _INFORMATION_DSP1,
    __module__ = 'information_pb2'
    # @@protoc_insertion_point(class_scope:Information.Dsp1)
    ))
  ,

  Dsp2 = _reflection.GeneratedProtocolMessageType('Dsp2', (_message.Message,), dict(
    DESCRIPTOR = _INFORMATION_DSP2,
    __module__ = 'information_pb2'
    # @@protoc_insertion_point(class_scope:Information.Dsp2)
    ))
  ,

  Errors = _reflection.GeneratedProtocolMessageType('Errors', (_message.Message,), dict(

    LoggerList = _reflection.GeneratedProtocolMessageType('LoggerList', (_message.Message,), dict(
      DESCRIPTOR = _INFORMATION_ERRORS_LOGGERLIST,
      __module__ = 'information_pb2'
      # @@protoc_insertion_point(class_scope:Information.Errors.LoggerList)
      ))
    ,
    DESCRIPTOR = _INFORMATION_ERRORS,
    __module__ = 'information_pb2'
    # @@protoc_insertion_point(class_scope:Information.Errors)
    ))
  ,
  DESCRIPTOR = _INFORMATION,
  __module__ = 'information_pb2'
  # @@protoc_insertion_point(class_scope:Information)
  ))
_sym_db.RegisterMessage(Information)
_sym_db.RegisterMessage(Information.Cpu)
_sym_db.RegisterMessage(Information.Dsp1)
_sym_db.RegisterMessage(Information.Dsp2)
_sym_db.RegisterMessage(Information.Errors)
_sym_db.RegisterMessage(Information.Errors.LoggerList)


# @@protoc_insertion_point(module_scope)
